tasks:
    - name: Copy Symfony Code
        command: cp -r symfony-my-hiking-map /home/tiagopin/symfony

  # - name: Install Composer Dependencies
  #   command: composer install
  #   root_directory: /home/tiagopin/symfony


# build_commands:
#   symfony:
#     - cd symfony-my-hiking-map
#     - composer install

#   vue:
#     - cd vue-my-hiking-map
#     - npm install
#     - npm run build

# deployment:
#   vue:
#     destination: /home/tiagopin/repositories

  # tasks:
  #   - export DEPLOYPATH=/home/tiagopin/repositories/my-hiking-map
  #   - export DEPLOYPATHFRONT=/home/tiagopin/repositories
  #   - /bin/cp -R ./vue-my-hiking-map/index.html $DEPLOYPATHFRONT
  #   - npm install --prefix ./vue-my-hiking-map
  #   - npm run build --prefix ./vue-my-hiking-map
  #   - /bin/cp -R vue-my-hiking-map/dist/* $DEPLOYPATHFRONT
    # - /bin/cp -R images $DEPLOYPATH
    # - /bin/cp -R images /home/tiagopin/repositories/my-hiking-map /home/tiagopin/repositories
    # - export DEPLOYPATHFRONT=/home/tiagopin/public_html/new_site/frontend
    # - /bin/cp -R frontend/* $DEPLOYPATHFRONT
    # - export DEPLOYPATHBACK=/home/tiagopin/public_html/new_site/backend
    # - /bin/cp -R backend/* $DEPLOYPATHBACK
    # - npm run build --prefix /home/tiagopin/public_html/new_site/backend
    # - npm run start --prefix /home/tiagopin/public_html/new_site/backend
    # - npm run build --prefix /home/tiagopin/public_html/new_site/frontend
    # - npm run start --prefix /home/tiagopin/public_html/new_site/frontend